/**
 * CURRICULUM: official CompTIA Security+ SY0-701 (v6.0) sub-topics per objective.
 * Each `term` is the exam's own enumerated bullet (lightly normalized). The
 * coverage test (tests/subtopics.test.ts) fails if any term is not taught on a
 * player-facing content surface. `aka` lists phrasings that also count.
 */
export interface SubtopicTerm {
  term: string;
  aka?: string[];
}

export interface ObjectiveSubtopics {
  summary: string;
  terms: SubtopicTerm[];
}

export const SUBTOPICS: Record<string, ObjectiveSubtopics> = {
  '1.1': {
    summary: 'Compare and contrast various types of security controls',
    terms: [
      { term: 'technical control' },
      { term: 'managerial control' },
      { term: 'operational control' },
      { term: 'physical control' },
      { term: 'preventive' },
      { term: 'deterrent' },
      { term: 'detective' },
      { term: 'corrective' },
      { term: 'compensating' },
      { term: 'directive' },
    ],
  },
  '1.2': {
    summary: 'Summarize fundamental security concepts',
    terms: [
      { term: 'confidentiality, integrity, and availability', aka: ['CIA triad', 'CIA)'] },
      { term: 'non-repudiation' },
      { term: 'authentication, authorization, and accounting', aka: ['AAA'] },
      { term: 'authenticating people' },
      { term: 'authenticating systems' },
      { term: 'authorization model' },
      { term: 'gap analysis' },
      { term: 'zero trust' },
      { term: 'control plane' },
      { term: 'adaptive identity' },
      { term: 'threat scope reduction' },
      { term: 'policy-driven access control' },
      { term: 'policy administrator' },
      { term: 'policy engine' },
      { term: 'data plane' },
      { term: 'implicit trust zone' },
      { term: 'policy enforcement point' },
      { term: 'bollard' },
      { term: 'access control vestibule' },
      { term: 'fencing' },
      { term: 'video surveillance' },
      { term: 'security guard' },
      { term: 'access badge' },
      { term: 'lighting' },
      { term: 'infrared' },
      { term: 'pressure sensor' },
      { term: 'microwave sensor' },
      { term: 'ultrasonic sensor' },
      { term: 'honeypot' },
      { term: 'honeynet' },
      { term: 'honeyfile' },
      { term: 'honeytoken' },
    ],
  },
  '1.3': {
    summary: 'Explain the importance of change management processes and the impact to security',
    terms: [
      { term: 'approval process' },
      { term: 'ownership' },
      { term: 'stakeholder' },
      { term: 'impact analysis' },
      { term: 'test results' },
      { term: 'backout plan' },
      { term: 'maintenance window' },
      { term: 'standard operating procedure' },
      { term: 'allow list' },
      { term: 'deny list' },
      { term: 'restricted activities' },
      { term: 'downtime' },
      { term: 'service restart' },
      { term: 'application restart' },
      { term: 'legacy application' },
      { term: 'dependencies' },
      { term: 'updating diagrams' },
      { term: 'version control' },
    ],
  },
  '1.4': {
    summary: 'Explain the importance of using appropriate cryptographic solutions',
    terms: [
      { term: 'public key infrastructure', aka: ['PKI'] },
      { term: 'public key' },
      { term: 'private key' },
      { term: 'key escrow' },
      { term: 'full-disk encryption' },
      { term: 'partition' },
      { term: 'file-level encryption' },
      { term: 'volume' },
      { term: 'database encryption' },
      { term: 'record-level encryption' },
      { term: 'transport encryption' },
      { term: 'asymmetric' },
      { term: 'symmetric' },
      { term: 'key exchange' },
      { term: 'algorithm' },
      { term: 'key length' },
      { term: 'trusted platform module', aka: ['TPM'] },
      { term: 'hardware security module', aka: ['HSM'] },
      { term: 'key management system' },
      { term: 'secure enclave' },
      { term: 'steganography' },
      { term: 'tokenization' },
      { term: 'data masking' },
      { term: 'hashing' },
      { term: 'salting' },
      { term: 'digital signature' },
      { term: 'key stretching' },
      { term: 'blockchain' },
      { term: 'open public ledger' },
      { term: 'certificate authority', aka: ['CA '] },
      { term: 'certificate revocation list', aka: ['CRL'] },
      { term: 'online certificate status protocol', aka: ['OCSP'] },
      { term: 'self-signed' },
      { term: 'third-party certificate' },
      { term: 'root of trust' },
      { term: 'certificate signing request', aka: ['CSR'] },
      { term: 'wildcard' },
    ],
  },
  '2.1': {
    summary: 'Compare and contrast common threat actors and motivations',
    terms: [
      { term: 'nation-state' },
      { term: 'unskilled attacker' },
      { term: 'hacktivist' },
      { term: 'insider threat' },
      { term: 'organized crime' },
      { term: 'shadow IT' },
      { term: 'internal actor', aka: ['internal/external'] },
      { term: 'external actor' },
      { term: 'resources and funding' },
      { term: 'level of sophistication' },
      { term: 'data exfiltration' },
      { term: 'espionage' },
      { term: 'service disruption' },
      { term: 'blackmail' },
      { term: 'financial gain' },
      { term: 'philosophical' },
      { term: 'political beliefs' },
      { term: 'ethical' },
      { term: 'revenge' },
      { term: 'disruption' },
      { term: 'war' },
    ],
  },
  '2.2': {
    summary: 'Explain common threat vectors and attack surfaces',
    terms: [
      { term: 'message-based' },
      { term: 'short message service', aka: ['SMS'] },
      { term: 'instant messaging' },
      { term: 'image-based' },
      { term: 'file-based' },
      { term: 'voice call' },
      { term: 'removable device' },
      { term: 'vulnerable software' },
      { term: 'unsupported systems' },
      { term: 'open service ports' },
      { term: 'default credentials' },
      { term: 'supply chain' },
      { term: 'managed service provider', aka: ['MSP'] },
      { term: 'vendor' },
      { term: 'supplier' },
      { term: 'unsecure networks' },
      { term: 'bluetooth' },
      { term: 'phishing' },
      { term: 'vishing' },
      { term: 'smishing' },
      { term: 'misinformation' },
      { term: 'disinformation' },
      { term: 'impersonation' },
      { term: 'business email compromise' },
      { term: 'pretexting' },
      { term: 'watering hole' },
      { term: 'brand impersonation' },
      { term: 'typosquatting' },
    ],
  },
  '2.3': {
    summary: 'Explain various types of vulnerabilities',
    terms: [
      { term: 'memory injection' },
      { term: 'buffer overflow' },
      { term: 'race condition' },
      { term: 'time-of-check', aka: ['TOC'] },
      { term: 'time-of-use', aka: ['TOU'] },
      { term: 'malicious update' },
      { term: 'OS-based' },
      { term: 'SQL injection', aka: ['SQLi'] },
      { term: 'cross-site scripting', aka: ['XSS'] },
      { term: 'firmware' },
      { term: 'end-of-life' },
      { term: 'legacy' },
      { term: 'VM escape' },
      { term: 'resource reuse' },
      { term: 'cloud-specific' },
      { term: 'cryptographic vulnerability', aka: ['cryptographic weakness'] },
      { term: 'misconfiguration' },
      { term: 'side loading' },
      { term: 'jailbreak' },
      { term: 'zero-day' },
    ],
  },
  '2.4': {
    summary: 'Given a scenario, analyze indicators of malicious activity',
    terms: [
      { term: 'ransomware' },
      { term: 'trojan' },
      { term: 'worm' },
      { term: 'spyware' },
      { term: 'bloatware' },
      { term: 'virus' },
      { term: 'keylogger' },
      { term: 'logic bomb' },
      { term: 'rootkit' },
      { term: 'brute force' },
      { term: 'RFID cloning' },
      { term: 'environmental' },
      { term: 'distributed denial-of-service', aka: ['DDoS'] },
      { term: 'amplified' },
      { term: 'reflected' },
      { term: 'DNS attack' },
      { term: 'on-path' },
      { term: 'credential replay' },
      { term: 'malicious code' },
      { term: 'injection' },
      { term: 'replay' },
      { term: 'privilege escalation' },
      { term: 'forgery' },
      { term: 'directory traversal' },
      { term: 'downgrade' },
      { term: 'collision' },
      { term: 'birthday' },
      { term: 'spraying' },
      { term: 'account lockout' },
      { term: 'concurrent session' },
      { term: 'blocked content' },
      { term: 'impossible travel' },
      { term: 'resource consumption' },
      { term: 'resource inaccessibility' },
      { term: 'out-of-cycle logging' },
      { term: 'published/documented' },
      { term: 'missing logs' },
    ],
  },
  '2.5': {
    summary: 'Explain the purpose of mitigation techniques used to secure the enterprise',
    terms: [
      { term: 'segmentation' },
      { term: 'access control list', aka: ['ACL'] },
      { term: 'permissions' },
      { term: 'application allow list' },
      { term: 'isolation' },
      { term: 'patching' },
      { term: 'encryption' },
      { term: 'monitoring' },
      { term: 'least privilege' },
      { term: 'configuration enforcement' },
      { term: 'decommissioning' },
      { term: 'hardening' },
      { term: 'endpoint protection' },
      { term: 'host-based firewall' },
      { term: 'host-based intrusion prevention', aka: ['HIPS'] },
      { term: 'disabling ports' },
      { term: 'default password' },
      { term: 'removal of unnecessary software' },
    ],
  },
  '3.1': {
    summary: 'Compare and contrast security implications of different architecture models',
    terms: [
      { term: 'cloud' },
      { term: 'responsibility matrix' },
      { term: 'hybrid' },
      { term: 'third-party' },
      { term: 'infrastructure as code', aka: ['IaC'] },
      { term: 'serverless' },
      { term: 'microservices' },
      { term: 'physical isolation' },
      { term: 'air-gapped' },
      { term: 'logical segmentation' },
      { term: 'software-defined networking', aka: ['SDN'] },
      { term: 'on-premises' },
      { term: 'centralized' },
      { term: 'decentralized' },
      { term: 'containerization' },
      { term: 'virtualization' },
      { term: 'IoT' },
      { term: 'ICS' },
      { term: 'SCADA' },
      { term: 'RTOS' },
      { term: 'embedded systems' },
      { term: 'high availability' },
      { term: 'availability' },
      { term: 'resilience' },
      { term: 'responsiveness' },
      { term: 'scalability' },
      { term: 'ease of deployment' },
      { term: 'risk transference' },
      { term: 'ease of recovery' },
      { term: 'patch availability' },
      { term: 'inability to patch' },
    ],
  },
  '3.2': {
    summary: 'Given a scenario, apply security principles to secure enterprise infrastructure',
    terms: [
      { term: 'port security' },
      { term: '802.1X' },
      { term: 'extensible authentication protocol', aka: ['EAP'] },
      { term: 'device placement' },
      { term: 'security zones' },
      { term: 'attack surface' },
      { term: 'connectivity' },
      { term: 'fail-open' },
      { term: 'fail-closed' },
      { term: 'active vs. passive' },
      { term: 'inline vs. tap' },
      { term: 'jump server' },
      { term: 'proxy server' },
      { term: 'intrusion prevention system', aka: ['IPS'] },
      { term: 'intrusion detection system', aka: ['IDS'] },
      { term: 'load balancer' },
      { term: 'sensors' },
      { term: 'SD-WAN' },
      { term: 'secure access service edge', aka: ['SASE'] },
      { term: 'web application firewall', aka: ['WAF'] },
      { term: 'unified threat management', aka: ['UTM'] },
      { term: 'next-generation firewall', aka: ['NGFW'] },
      { term: 'layer 4' },
      { term: 'layer 7' },
      { term: 'virtual private network', aka: ['VPN'] },
      { term: 'remote access' },
      { term: 'tunneling' },
      { term: 'transport layer security', aka: ['TLS'] },
      { term: 'IPSec' },
    ],
  },
  '3.3': {
    summary: 'Compare and contrast concepts and strategies to protect data',
    terms: [
      { term: 'regulated' },
      { term: 'trade secret' },
      { term: 'intellectual property' },
      { term: 'legal information' },
      { term: 'financial information' },
      { term: 'human-readable' },
      { term: 'non-human-readable' },
      { term: 'sensitive' },
      { term: 'confidential' },
      { term: 'public' },
      { term: 'restricted' },
      { term: 'private' },
      { term: 'critical' },
      { term: 'data at rest' },
      { term: 'data in transit' },
      { term: 'data in use' },
      { term: 'data sovereignty' },
      { term: 'geolocation' },
      { term: 'geographic restrictions' },
      { term: 'masking' },
      { term: 'obfuscation' },
      { term: 'permission restrictions' },
    ],
  },
  '3.4': {
    summary: 'Explain the importance of resilience and recovery in security architecture',
    terms: [
      { term: 'high availability' },
      { term: 'load balancing' },
      { term: 'clustering' },
      { term: 'hot site' },
      { term: 'cold site' },
      { term: 'warm site' },
      { term: 'geographic dispersion' },
      { term: 'platform diversity' },
      { term: 'multi-cloud' },
      { term: 'continuity of operations' },
      { term: 'capacity planning' },
      { term: 'tabletop exercise' },
      { term: 'fail over' },
      { term: 'simulation' },
      { term: 'parallel processing' },
      { term: 'onsite' },
      { term: 'offsite' },
      { term: 'frequency' },
      { term: 'snapshots' },
      { term: 'recovery' },
      { term: 'replication' },
      { term: 'journaling' },
      { term: 'generator' },
      { term: 'uninterruptible power supply', aka: ['UPS'] },
    ],
  },
  '4.1': {
    summary: 'Given a scenario, apply common security techniques to computing resources',
    terms: [
      { term: 'secure baseline' },
      { term: 'hardening' },
      { term: 'mobile devices' },
      { term: 'workstations' },
      { term: 'switches' },
      { term: 'routers' },
      { term: 'cloud infrastructure' },
      { term: 'servers' },
      { term: 'site survey' },
      { term: 'heat map' },
      { term: 'WPA3' },
      { term: 'RADIUS' },
      { term: 'TACACS+' },
      { term: 'cryptographic protocols' },
      { term: 'authentication protocols' },
      { term: 'mobile device management', aka: ['MDM'] },
      { term: 'bring your own device', aka: ['BYOD'] },
      { term: 'corporate-owned, personally enabled', aka: ['COPE'] },
      { term: 'choose your own device', aka: ['CYOD'] },
      { term: 'cellular' },
      { term: 'input validation' },
      { term: 'secure cookies' },
      { term: 'static code analysis' },
      { term: 'code signing' },
      { term: 'sandboxing' },
    ],
  },
  '4.2': {
    summary: 'Explain the security implications of proper hardware, software, and data asset management',
    terms: [
      { term: 'acquisition' },
      { term: 'procurement' },
      { term: 'assignment' },
      { term: 'accounting' },
      { term: 'ownership' },
      { term: 'classification' },
      { term: 'asset tracking' },
      { term: 'inventory' },
      { term: 'enumeration' },
      { term: 'disposal' },
      { term: 'decommissioning' },
      { term: 'sanitization' },
      { term: 'destruction' },
      { term: 'certification' },
      { term: 'data retention' },
    ],
  },
  '4.3': {
    summary: 'Explain various activities associated with vulnerability management',
    terms: [
      { term: 'vulnerability scan' },
      { term: 'static analysis' },
      { term: 'dynamic analysis' },
      { term: 'package monitoring' },
      { term: 'threat feed' },
      { term: 'open-source intelligence', aka: ['OSINT'] },
      { term: 'information-sharing organization' },
      { term: 'dark web' },
      { term: 'penetration testing' },
      { term: 'responsible disclosure' },
      { term: 'bug bounty' },
      { term: 'system audit' },
      { term: 'false positive' },
      { term: 'false negative' },
      { term: 'compensating controls' },
      { term: 'exception' },
      { term: 'exemption' },
      { term: 'rescanning' },
      { term: 'validation of remediation' },
      { term: 'prioritize' },
      { term: 'common vulnerability scoring system', aka: ['CVSS'] },
      { term: 'common vulnerability enumeration', aka: ['CVE'] },
      { term: 'exposure factor' },
      { term: 'risk tolerance' },
      { term: 'insurance' },
    ],
  },
  '4.4': {
    summary: 'Explain security alerting and monitoring concepts and tools',
    terms: [
      { term: 'log aggregation' },
      { term: 'alerting' },
      { term: 'scanning' },
      { term: 'archiving' },
      { term: 'quarantine' },
      { term: 'alert tuning' },
      { term: 'security content automation protocol', aka: ['SCAP'] },
      { term: 'benchmark' },
      { term: 'agentless' },
      { term: 'security information and event management', aka: ['SIEM'] },
      { term: 'antivirus' },
      { term: 'data loss prevention', aka: ['DLP'] },
      { term: 'SNMP traps' },
      { term: 'NetFlow' },
      { term: 'vulnerability scanners' },
    ],
  },
  '4.5': {
    summary: 'Given a scenario, modify enterprise capabilities to enhance security',
    terms: [
      { term: 'firewall rules' },
      { term: 'access lists' },
      { term: 'screened subnet' },
      { term: 'signatures' },
      { term: 'web filter' },
      { term: 'centralized proxy' },
      { term: 'URL scanning' },
      { term: 'content categorization' },
      { term: 'block rules' },
      { term: 'reputation' },
      { term: 'protocol selection' },
      { term: 'port selection' },
      { term: 'DNS filtering' },
      { term: 'DMARC' },
      { term: 'DKIM' },
      { term: 'sender policy framework', aka: ['SPF'] },
      { term: 'gateway' },
      { term: 'file integrity monitoring' },
      { term: 'network access control', aka: ['NAC'] },
      { term: 'endpoint detection and response', aka: ['EDR'] },
      { term: 'extended detection and response', aka: ['XDR'] },
      { term: 'user behavior analytics' },
      { term: 'group policy' },
      { term: 'SELinux' },
    ],
  },
  '4.6': {
    summary: 'Given a scenario, implement and maintain identity and access management',
    terms: [
      { term: 'provisioning' },
      { term: 'de-provisioning' },
      { term: 'permission assignments' },
      { term: 'identity proofing' },
      { term: 'federation' },
      { term: 'single sign-on', aka: ['SSO'] },
      { term: 'lightweight directory access protocol', aka: ['LDAP'] },
      { term: 'OAuth' },
      { term: 'security assertions markup language', aka: ['SAML'] },
      { term: 'interoperability' },
      { term: 'attestation' },
      { term: 'mandatory access control' },
      { term: 'discretionary access control' },
      { term: 'role-based' },
      { term: 'rule-based' },
      { term: 'attribute-based' },
      { term: 'time-of-day restrictions' },
      { term: 'biometrics' },
      { term: 'hard token' },
      { term: 'soft token' },
      { term: 'security keys' },
      { term: 'something you know' },
      { term: 'something you have' },
      { term: 'something you are' },
      { term: 'somewhere you are' },
      { term: 'password manager' },
      { term: 'passwordless' },
      { term: 'just-in-time' },
      { term: 'password vaulting' },
      { term: 'ephemeral credentials' },
    ],
  },
  '4.7': {
    summary: 'Explain the importance of automation and orchestration related to secure operations',
    terms: [
      { term: 'user provisioning' },
      { term: 'resource provisioning' },
      { term: 'guard rails' },
      { term: 'security groups' },
      { term: 'ticket creation' },
      { term: 'escalation' },
      { term: 'enabling and disabling services' },
      { term: 'continuous integration' },
      { term: 'APIs' },
      { term: 'efficiency' },
      { term: 'enforcing baselines' },
      { term: 'standard infrastructure configurations' },
      { term: 'scaling' },
      { term: 'employee retention' },
      { term: 'reaction time' },
      { term: 'workforce multiplier' },
      { term: 'complexity' },
      { term: 'single point of failure' },
      { term: 'technical debt' },
      { term: 'ongoing supportability' },
    ],
  },
  '4.8': {
    summary: 'Explain appropriate incident response activities',
    terms: [
      { term: 'preparation' },
      { term: 'detection' },
      { term: 'analysis' },
      { term: 'containment' },
      { term: 'eradication' },
      { term: 'recovery' },
      { term: 'lessons learned' },
      { term: 'tabletop exercise' },
      { term: 'simulation' },
      { term: 'root cause analysis' },
      { term: 'threat hunting' },
      { term: 'digital forensics' },
      { term: 'legal hold' },
      { term: 'chain of custody' },
      { term: 'acquisition' },
      { term: 'preservation' },
      { term: 'e-discovery' },
    ],
  },
  '4.9': {
    summary: 'Given a scenario, use data sources to support an investigation',
    terms: [
      { term: 'firewall logs' },
      { term: 'application logs' },
      { term: 'endpoint logs' },
      { term: 'security logs' },
      { term: 'IPS/IDS logs' },
      { term: 'network logs' },
      { term: 'metadata' },
      { term: 'vulnerability scans' },
      { term: 'automated reports' },
      { term: 'dashboards' },
      { term: 'packet captures' },
    ],
  },
  '5.1': {
    summary: 'Summarize elements of effective security governance',
    terms: [
      { term: 'guidelines' },
      { term: 'acceptable use policy', aka: ['AUP'] },
      { term: 'information security policy' },
      { term: 'business continuity' },
      { term: 'disaster recovery' },
      { term: 'incident response' },
      { term: 'software development lifecycle', aka: ['SDLC'] },
      { term: 'change management' },
      { term: 'password standards' },
      { term: 'access control standards' },
      { term: 'physical security standards' },
      { term: 'encryption standards' },
      { term: 'onboarding' },
      { term: 'offboarding' },
      { term: 'playbooks' },
      { term: 'regulatory' },
      { term: 'industry' },
      { term: 'board' },
      { term: 'committee' },
      { term: 'government entities' },
      { term: 'owners' },
      { term: 'controllers' },
      { term: 'processors' },
      { term: 'custodians' },
      { term: 'stewards' },
    ],
  },
  '5.2': {
    summary: 'Explain elements of the risk management process',
    terms: [
      { term: 'risk reporting' },
      { term: 'business impact analysis', aka: ['BIA'] },
      { term: 'recovery time objective', aka: ['RTO'] },
      { term: 'recovery point objective', aka: ['RPO'] },
      { term: 'mean time to repair', aka: ['MTTR'] },
      { term: 'mean time between failures', aka: ['MTBF'] },
      { term: 'risk identification' },
      { term: 'risk assessment' },
      { term: 'qualitative' },
      { term: 'quantitative' },
      { term: 'single loss expectancy', aka: ['SLE'] },
      { term: 'annualized loss expectancy', aka: ['ALE'] },
      { term: 'annualized rate of occurrence', aka: ['ARO'] },
      { term: 'probability' },
      { term: 'likelihood' },
      { term: 'impact' },
      { term: 'risk register' },
      { term: 'key risk indicator', aka: ['KRI'] },
      { term: 'risk owner' },
      { term: 'risk threshold' },
      { term: 'risk tolerance' },
      { term: 'risk appetite' },
      { term: 'expansionary' },
      { term: 'conservative' },
      { term: 'transfer' },
      { term: 'accept' },
      { term: 'avoid' },
      { term: 'mitigate' },
    ],
  },
  '5.3': {
    summary: 'Explain the processes associated with third-party risk assessment and management',
    terms: [
      { term: 'vendor assessment' },
      { term: 'penetration testing' },
      { term: 'right-to-audit' },
      { term: 'evidence of internal audits' },
      { term: 'independent assessments' },
      { term: 'supply chain analysis' },
      { term: 'due diligence' },
      { term: 'conflict of interest' },
      { term: 'vendor monitoring' },
      { term: 'questionnaire' },
      { term: 'rules of engagement' },
      { term: 'service-level agreement', aka: ['SLA'] },
      { term: 'memorandum of agreement', aka: ['MOA'] },
      { term: 'memorandum of understanding', aka: ['MOU'] },
      { term: 'master service agreement', aka: ['MSA'] },
      { term: 'statement of work', aka: ['SOW'] },
      { term: 'business partners agreement', aka: ['BPA'] },
      { term: 'non-disclosure agreement', aka: ['NDA'] },
    ],
  },
  '5.4': {
    summary: 'Summarize elements of effective security compliance',
    terms: [
      { term: 'compliance reporting' },
      { term: 'internal reporting' },
      { term: 'external reporting' },
      { term: 'fines' },
      { term: 'sanctions' },
      { term: 'reputational damage' },
      { term: 'loss of license' },
      { term: 'contractual impacts' },
      { term: 'due diligence' },
      { term: 'due care' },
      { term: 'attestation' },
      { term: 'acknowledgement' },
      { term: 'automation' },
      { term: 'data subject' },
      { term: 'controller' },
      { term: 'processor' },
      { term: 'data inventory' },
      { term: 'right to be forgotten' },
    ],
  },
  '5.5': {
    summary: 'Explain types and purposes of audits and assessments',
    terms: [
      { term: 'attestation' },
      { term: 'internal audit' },
      { term: 'audit committee' },
      { term: 'self-assessment' },
      { term: 'external audit' },
      { term: 'examinations' },
      { term: 'independent third-party audit' },
      { term: 'penetration testing' },
      { term: 'offensive' },
      { term: 'defensive' },
      { term: 'integrated' },
      { term: 'known environment' },
      { term: 'partially known environment' },
      { term: 'unknown environment' },
      { term: 'reconnaissance' },
      { term: 'passive reconnaissance' },
      { term: 'active reconnaissance' },
    ],
  },
  '5.6': {
    summary: 'Given a scenario, implement security awareness practices',
    terms: [
      { term: 'phishing campaign' },
      { term: 'recognizing a phishing attempt' },
      { term: 'reported suspicious messages' },
      { term: 'risky' },
      { term: 'unexpected' },
      { term: 'unintentional' },
      { term: 'policy handbook' },
      { term: 'situational awareness' },
      { term: 'password management' },
      { term: 'removable media' },
      { term: 'social engineering' },
      { term: 'operational security' },
      { term: 'remote work' },
      { term: 'initial reporting' },
      { term: 'recurring' },
      { term: 'development' },
      { term: 'execution' },
    ],
  },
};

/** All sub-topic terms across the catalog, flattened with their objective id. */
export function allSubtopics(): { objective: string; term: SubtopicTerm }[] {
  return Object.entries(SUBTOPICS).flatMap(([objective, s]) =>
    s.terms.map((term) => ({ objective, term })),
  );
}
