import type { Mission } from '../../core/types';
import { lightRects } from '../../missions/levelkit';
import type { WalkStep } from '../../missions/walkthroughs';
import type { MissionTeaching } from '../curriculum';
import { q } from '../arc-questions';

export const m06: Mission = {
  id: 'm06',
  title: 'KEYMASTER',
  difficulty: 7,
  objectives: ['1.4', '3.3', '4.6'],
  briefing:
    'KEYMASTER security audit, 2026-10-05. An expired certificate, a leaked VPN key and exposed card data are blocking release. ' +
    'Your kit: KEYBOARD (1) operates consoles, MOUSE (2) inspects, BADGE (4) presents your role, and MFA TOKEN (7) confirms a second factor.',
  authorizedRoles: ['analyst'],
  loadout: ['keyboard', 'mouse', 'usb', 'badge', 'mfa'],
  map: {
    grid: [
      '########################################',
      '########################################',
      '################........################',
      '##............##....E...##............##',
      '##............##........##............##',
      '##............######X#####............##',
      '##............#..........#....SS..SS..##',
      '##............#..........#....SS..SS..##',
      '##....B...B...#...S..S...#....SS..SS..##',
      '##....B...B...#...S..S...#....SS..SS..##',
      '##....B.......#...S..S...#....SS..SS..##',
      '##............#..........#............##',
      '##..........B.######M#####............##',
      '##............#..........#............##',
      '##............#..........#............##',
      '##............#..B.....B.#............##',
      '##............#..........#............##',
      '########C######..........######K########',
      '##..................B.................##',
      '##....................................##',
      '##....................................##',
      '######............................######',
      '##...#............................#...##',
      '##...1............................2...##',
      '##...#............................#...##',
      '######............................######',
      '##....................................##',
      '##....................................##',
      '########################################',
      '########################################',
    ],
    legend: {
      '#': { kind: 'wall', tex: 'wall-panel' },
      S: { kind: 'wall', tex: 'wall-server' },
      B: { kind: 'wall', tex: 'wall-brick' },
      '.': { kind: 'floor', tex: 'floor' },
      E: { kind: 'exit', tex: 'exit' },
      C: { kind: 'door', tex: 'door', doorId: 'cert-gate' },
      K: { kind: 'door', tex: 'door', doorId: 'key-room' },
      M: { kind: 'door', tex: 'door', doorId: 'vault', accessRole: 'vault', mfa: true },
      X: {
        kind: 'door',
        tex: 'door',
        doorId: 'exit',
        locked: true,
        lockText: 'Exit opens after the vault audit passes.',
      },
      '1': { kind: 'door', tex: 'wall-brick', doorId: 'secret-cert-store', secret: true },
      '2': { kind: 'door', tex: 'wall-brick', doorId: 'secret-key-store', secret: true },
    },
    spawn: { x: 20.5, y: 25.5, angle: -Math.PI / 2 },
    defaultLight: 0.65,
    lights: lightRects([
      [2, 3, 13, 16, 0.5],
      [26, 3, 37, 16, 0.45],
      [15, 2, 24, 11, 0.75],
      [15, 13, 24, 18, 0.6],
      [2, 19, 37, 27, 0.9],
      [2, 22, 4, 24, 0.35],
      [35, 22, 37, 24, 0.35],
    ]),
  },
  entities: [
    {
      id: 'cert-a',
      kind: 'console',
      x: 3.5,
      y: 5.5,
      sprite: 'console',
      tags: ['cert', 'cert-ok'],
      inspect: {
        label: 'Certificate A: shop.keymaster.example',
        detail: 'Subject: shop.keymaster.example. Issuer: KeyMaster Issuing CA 2. Chain: leaf -> KeyMaster Issuing CA 2 -> GlobalTrust Root (in trust store). Signatures verify at every link. Valid: 2026-03-01 to 2027-03-01. OCSP: good.',
        category: 'legit',
        objectives: ['1.4'],
      },
      log: 'Certificate A installed on the TLS gateway. Clients validate the chain to a trusted root.',
    },
    {
      id: 'cert-b',
      kind: 'console',
      x: 8.5,
      y: 5.5,
      sprite: 'console',
      tags: ['cert', 'wrong'],
      inspect: {
        label: 'Certificate B: shop.keymaster.example',
        detail: 'Subject: shop.keymaster.example. Issuer: KeyMaster Issuing CA 2. Chain verifies to GlobalTrust Root. Valid: 2025-09-01 to 2026-09-01.',
        category: 'legit',
        objectives: ['1.4'],
      },
      log: 'Gateway refused: certificate expired 2026-09-01. Browsers would show a warning and block the site.',
    },
    {
      id: 'cert-c',
      kind: 'console',
      x: 12.5,
      y: 5.5,
      sprite: 'console',
      tags: ['cert', 'wrong'],
      inspect: {
        label: 'Certificate C: shop.keymaster.example',
        detail: 'Subject: shop.keymaster.example. Issuer: shop.keymaster.example. Chain: none (issuer = subject). Not in any trust store. Valid: 2026-10-01 to 2036-10-01.',
        category: 'legit',
        objectives: ['1.4'],
      },
      log: 'Self-signed certificate installed: no CA vouches for it, so every client warns, and anyone can mint an identical one.',
    },
    {
      id: 'leak-feed',
      kind: 'console',
      x: 27.5,
      y: 4.5,
      sprite: 'console',
      tags: ['leak'],
      inspect: {
        label: 'Paste-site alert',
        detail: '03:12 paste site: -----BEGIN PRIVATE KEY----- (2,048-bit RSA). Public-key fingerprint 9F:2C:...:41 matches vpn.keymaster.example certificate serial 0x5A11.',
        category: 'legit',
        objectives: ['1.4'],
      },
    },
    {
      id: 'ca-revoke',
      kind: 'console',
      x: 27.5,
      y: 6.5,
      sprite: 'console',
      priority: 1,
      tags: ['rotate'],
      inspect: {
        label: 'Issuing CA console',
        detail: 'Certificate vpn.keymaster.example serial 0x5A11: status good. CRL published hourly; OCSP responder online.',
        category: 'legit',
        objectives: ['1.4'],
      },
      log: 'Serial 0x5A11 revoked (key compromise). CRL and OCSP now report it revoked.',
    },
    {
      id: 'hsm-rekey',
      kind: 'console',
      x: 36.5,
      y: 6.5,
      sprite: 'console',
      priority: 2,
      tags: ['rotate'],
      grants: { resource: 'role:vault', amount: 1 },
      inspect: {
        label: 'HSM key ceremony',
        detail: 'Generate a new key pair inside the HSM and submit a CSR. Private keys never leave the HSM.',
        category: 'legit',
        objectives: ['1.4'],
      },
      log: 'New 3,072-bit key pair generated in the HSM. Replacement certificate issued with the new key. Old key retired.',
    },
    {
      id: 'renew-same',
      kind: 'console',
      x: 27.5,
      y: 11.5,
      sprite: 'console',
      tags: ['wrong'],
      inspect: {
        label: 'Quick renew (keep existing key)',
        detail: 'One click: extends vpn.keymaster.example for 12 months using the current key pair.',
        category: 'legit',
        objectives: ['1.4'],
      },
      log: 'Renewal reused the leaked private key: whoever holds the paste can still impersonate the VPN.',
    },
    {
      id: 'pw-db',
      kind: 'console',
      x: 36.5,
      y: 11.5,
      sprite: 'workstation',
      tags: ['pw-evidence'],
      inspect: {
        label: 'Users table sample',
        detail: 'users.password: 5f4dcc3b5aa765d61d8327deb882cf99 (32 hex chars, unsalted) - identical value on 212 accounts.',
        category: 'legit',
        objectives: ['1.4'],
      },
    },
    {
      id: 'pw-aes',
      kind: 'console',
      x: 27.5,
      y: 14.5,
      sprite: 'console',
      tags: ['wrong'],
      inspect: {
        label: 'Option: encrypt passwords with AES',
        detail: 'Key stored in /etc/app/key on the same server.',
        category: 'legit',
        objectives: ['1.4'],
      },
      log: 'Encryption is reversible: steal the database and the key and you have every password.',
    },
    {
      id: 'pw-bcrypt',
      kind: 'console',
      x: 32.5,
      y: 14.5,
      sprite: 'console',
      tags: ['pw-fix'],
      inspect: {
        label: 'Option: salted bcrypt',
        detail: 'Unique random salt per user, bcrypt cost 12; rehash at next login.',
        category: 'legit',
        objectives: ['1.4'],
      },
      log: 'Passwords now salted and key-stretched: no rainbow tables, every guess expensive.',
    },
    {
      id: 'pw-b64',
      kind: 'console',
      x: 36.5,
      y: 14.5,
      sprite: 'console',
      tags: ['wrong'],
      inspect: {
        label: 'Option: Base64-encode passwords',
        detail: 'Encode the password column as Base64.',
        category: 'legit',
        objectives: ['1.4'],
      },
      log: 'Base64 is encoding, not crypto: anyone can decode it.',
    },
    {
      id: 'admin-gate',
      kind: 'console',
      x: 16.5,
      y: 7.5,
      sprite: 'console',
      tags: ['mfa-know', 'wrong'],
      inspect: {
        label: 'Legacy admin sign-in',
        detail: "Factors: password + security question (mother's maiden name).",
        category: 'legit',
        objectives: ['4.6'],
      },
      log: 'Two things you know is still one factor type. Not MFA.',
    },
    {
      id: 'card-export',
      kind: 'console',
      x: 16.5,
      y: 9.5,
      sprite: 'workstation',
      tags: ['data-protect'],
      inspect: {
        label: 'Refund export job',
        detail: 'Nightly export to the refunds system: card_number 4111 1111 1111 1111 (full PAN, plaintext CSV).',
        category: 'legit',
        objectives: ['3.3'],
      },
      log: 'Card numbers replaced with tokens; only the token vault can map them back. Refunds keep working.',
    },
    {
      id: 'backup-disk',
      kind: 'console',
      x: 23.5,
      y: 9.5,
      sprite: 'workstation',
      tags: ['data-protect'],
      inspect: {
        label: 'Backup disk shelf',
        detail: 'Nightly backup drives, removable, encryption: off.',
        category: 'legit',
        objectives: ['3.3'],
      },
      log: 'Full-disk encryption enabled on the backup drives: data at rest is unreadable without the key.',
    },
    {
      id: 'vault-exit-console',
      kind: 'console',
      x: 20.5,
      y: 10.5,
      sprite: 'console',
      tags: ['seal'],
      inspect: {
        label: 'Vault audit console',
        detail: 'Audit checklist for the vault.',
        category: 'legit',
        objectives: ['1.4', '3.3'],
      },
      log: 'Audit passed: chain trusted, compromised key rotated, passwords hashed, card data tokenized, backups encrypted at rest.',
    },
    {
      id: 'find-edr',
      kind: 'item',
      x: 17.5,
      y: 19.5,
      sprite: 'tool-edr',
      tags: ['arsenal-pickup'],
      grants: { resource: 'tool:edr', amount: 1 },
      inspect: { label: 'EDR console (found)', detail: 'Endpoint detection and response console with containment.', category: 'item', objectives: ['4.5'] },
    },
    {
      id: 'edr-cell-a',
      kind: 'item',
      x: 10.5,
      y: 22.5,
      sprite: 'edr-cell',
      tags: ['arsenal-pickup'],
      grants: { resource: 'edr-cell', amount: 1 },
      inspect: { label: 'EDR cell', detail: 'Licence and compute for one EDR containment pulse.', category: 'item', objectives: ['4.5'] },
    },
    {
      id: 'edr-cell-b',
      kind: 'item',
      x: 29.5,
      y: 22.5,
      sprite: 'edr-cell',
      tags: ['arsenal-pickup'],
      grants: { resource: 'edr-cell', amount: 1 },
      inspect: { label: 'EDR cell', detail: 'Licence and compute for one EDR containment pulse.', category: 'item', objectives: ['4.5'] },
    },
    ...(
      [
        ['usb-charge-a', 4.5, 26.5],
        ['usb-charge-b', 14.5, 22.5],
        ['usb-charge-c', 35.5, 26.5],
      ] as const
    ).map(([id, x, y]) => ({
      id,
      kind: 'item' as const,
      x,
      y,
      sprite: 'charge',
      tags: ['arsenal-pickup'],
      grants: { resource: 'usb-charge', amount: 4 },
      inspect: { label: 'Scanner charges', detail: 'Antimalware definitions for the USB scanner.', category: 'item' as const },
    })),
    {
      id: 'secret-medkit-a',
      kind: 'item',
      x: 3.5,
      y: 23.5,
      sprite: 'medkit',
      grants: { resource: 'integrity', amount: 25 },
      inspect: { label: 'Integrity kit', detail: 'Restores 25 integrity.', category: 'item' },
    },
    {
      id: 'secret-medkit-b',
      kind: 'item',
      x: 36.5,
      y: 23.5,
      sprite: 'medkit',
      grants: { resource: 'integrity', amount: 25 },
      inspect: { label: 'Integrity kit', detail: 'Restores 25 integrity.', category: 'item' },
    },
    {
      id: 'key-worm-a',
      kind: 'enemy',
      x: 28.5,
      y: 3.5,
      sprite: 'worm',
      ai: 'chase',
      hp: 2,
      infected: true,
      dormant: true,
      tags: ['malware'],
      inspect: { label: 'Worm', detail: 'The worm is probing the systems that manage certificates and keys.', category: 'malware', objectives: ['2.4'] },
    },
    {
      id: 'key-worm-b',
      kind: 'enemy',
      x: 36.5,
      y: 15.5,
      sprite: 'worm',
      ai: 'chase',
      hp: 2,
      infected: true,
      dormant: true,
      tags: ['malware'],
      inspect: { label: 'Worm', detail: 'The worm is probing the systems that manage certificates and keys.', category: 'malware', objectives: ['2.4'] },
    },
    {
      id: 'vault-trojan-a',
      kind: 'enemy',
      x: 16.5,
      y: 10.5,
      sprite: 'trojan',
      ai: 'chase',
      hp: 3,
      infected: true,
      dormant: true,
      tags: ['malware'],
      inspect: { label: 'Trojan', detail: 'A fake refund utility is targeting card data.', category: 'malware', objectives: ['2.4'] },
    },
    {
      id: 'vault-trojan-b',
      kind: 'enemy',
      x: 23.5,
      y: 7.5,
      sprite: 'trojan',
      ai: 'chase',
      hp: 3,
      infected: true,
      dormant: true,
      tags: ['malware'],
      inspect: { label: 'Trojan', detail: 'A fake refund utility is targeting card data.', category: 'malware', objectives: ['2.4'] },
    },
    {
      id: 'hall-worm',
      kind: 'enemy',
      x: 18.5,
      y: 18.5,
      sprite: 'worm',
      ai: 'wander',
      hp: 2,
      infected: true,
      tags: ['malware'],
      inspect: { label: 'Network worm', detail: 'The worm is moving through the lobby corridor.', category: 'malware', objectives: ['2.4'] },
    },
  ],
  missionObjectives: [
    { id: 'verify', text: 'Inspect every certificate offered to the gateway', kind: 'inspect', tag: 'cert', count: 3 },
    { id: 'install', text: 'Install a trustworthy certificate on the gateway', kind: 'interact', tag: 'cert-ok', requires: ['verify'] },
    { id: 'leak', text: 'Investigate the key alert', kind: 'inspect', tag: 'leak' },
    { id: 'rotate', text: 'Respond to the compromised key', kind: 'interact', tag: 'rotate', count: 2, ordered: true, requires: ['leak'] },
    { id: 'passwords', text: 'Fix password storage', kind: 'interact', tag: 'pw-fix', requires: ['install'] },
    { id: 'data', text: 'Protect the vault data', kind: 'interact', tag: 'data-protect', count: 2 },
    { id: 'seal', text: 'Pass the vault audit', kind: 'interact', tag: 'seal', requires: ['install', 'rotate', 'passwords', 'data'] },
    { id: 'exit', text: 'Reach the exit', kind: 'reach-exit' },
  ],
  debriefQuestions: [
    q('q1', ['1.4'], 'You must store user passwords so that a thief who dumps the database cannot reverse them or look them up in precomputed tables. What is BEST?', 2, [
      ['Encrypt them with AES, with the key on the same server', 'Encryption is reversible. Whoever steals the database and the key gets every password.'],
      ['Hash them with unsalted SHA-256', 'Unsalted fast hashes fall to rainbow tables and GPU brute force, and identical passwords produce identical hashes.'],
      ['Salt each password and hash it with a key-stretching algorithm (bcrypt, PBKDF2)', 'Salting defeats precomputed tables, and key stretching makes every guess expensive. Hashing is one-way, so nothing can be decrypted.'],
      ['Base64-encode them', 'Base64 is encoding, not cryptography. Anyone can decode it instantly.'],
    ]),
    q('q2', ['1.4'], 'The private key for www.example.com has leaked. What must happen to the certificate?', 3, [
      ['Nothing until it expires next year', 'Until then, anyone holding the key can impersonate the site with a certificate browsers still trust.'],
      ['Renew it with the same key pair', 'The leaked key would still be valid, so the compromise carries over to the new certificate.'],
      ['Replace it with a self-signed certificate', 'Browsers do not trust self-signed certificates, and the leaked certificate would still be valid.'],
      ['Revoke it so it appears on the CRL / OCSP, then reissue it with a new key pair', 'Revocation tells clients to stop trusting the compromised certificate. A new key pair ends the attacker\u2019s ability to impersonate the site.'],
    ]),
    q('q3', ['1.4'], 'A browser and a server that have never communicated must agree on a fast bulk-encryption key over the open internet. How does TLS do it?', 0, [
      ['Asymmetric key exchange (e.g. Diffie-Hellman) to agree a symmetric session key', 'Asymmetric crypto solves secure key exchange between strangers, and the symmetric session key then encrypts the bulk data quickly.'],
      ['The server emails the symmetric key in advance', 'That moves the key-distribution problem to email, which is not secure.'],
      ['Both sides hash the data instead of encrypting it', 'Hashing is one-way and provides integrity, not confidentiality. The other side could not read the data.'],
      ['Steganography hides the key inside an image', 'Steganography is obscurity, not encryption. Anyone who finds the hidden key can use it.'],
    ]),
    q('q4', ['3.3'], 'A payment app must keep issuing refunds against stored cards, but the systems that hold those records must not contain real card numbers. What is BEST?', 1, [
      ['Masking the numbers on screen', 'Masking hides digits when displayed, but the full number is still stored underneath.'],
      ['Tokenization', 'A random token replaces the card number, and only the secure token vault can map it back. Downstream systems hold nothing of value.'],
      ['Hashing the numbers', 'Hashing is one-way, so the original number could never be recovered to process refunds.'],
      ['Moving the database to another country', 'That changes data sovereignty, not exposure. The real numbers would still be stored.'],
    ]),
    q('q5', ['4.6'], 'Admin sign-in currently requires a password plus a security question. Which change adds a genuinely different authentication factor?', 2, [
      ['Require a longer password', 'A stronger password is still the same single factor: something you know.'],
      ['Add a second security question', 'Security questions are also something you know, so this is still one factor type.'],
      ['Add a FIDO2 hardware security key', 'A security key is something you have. Combined with the password, that is true MFA, and FIDO2 also resists phishing.'],
      ['Add a 6-digit PIN', 'A PIN is also something you know.'],
    ]),
    q('q6', ['3.3'], 'A stolen laptop had full-disk encryption, and the thief never got the pre-boot password. Which data state did that encryption protect?', 2, [
      ['Data in transit', 'In transit is data moving across a network, which TLS or a VPN protects.'],
      ['Data in use', 'In use is data being processed in memory by a running system. A powered-off stolen laptop is not processing anything.'],
      ['Data at rest', 'Data stored on the drive is at rest. Full-disk encryption keeps it unreadable without the key.'],
      ['Data sovereignty', 'Sovereignty is about which jurisdiction\u2019s laws apply to data. It is not a data state.'],
    ]),
  ],
  script: {
    par: 240,
    triggers: [
      {
        id: 'key-room-worms',
        area: [26, 3, 37, 16],
        spawn: ['key-worm-a', 'key-worm-b'],
        kind: 'warn',
        message: 'Attack traffic: worms are probing the key-management room!',
      },
      {
        id: 'vault-trojans',
        area: [15, 6, 24, 11],
        spawn: ['vault-trojan-a', 'vault-trojan-b'],
        kind: 'warn',
        message: 'Attackers want the card data!',
      },
      {
        id: 'audit-exit',
        after: ['seal'],
        openDoors: ['exit'],
        kind: 'good',
        message: 'Audit passed. Exit open.',
      },
    ],
    secrets: [
      { id: 'cert-store', area: [2, 22, 4, 24], label: 'Certificate storage closet' },
      { id: 'key-store', area: [35, 22, 37, 24], label: 'Key recovery closet' },
    ],
  },
};

export const m06Walkthrough: WalkStep[] = [
  { goto: [8, 18] },
  { badge: [8, 17] },
  { goto: [3, 5] },
  { inspect: 'cert-a' },
  { goto: [8, 5] },
  { inspect: 'cert-b' },
  { goto: [12, 5] },
  { inspect: 'cert-c' },
  { goto: [3, 5] },
  { interact: 'cert-a' },
  { goto: [8, 16] },
  { badge: [8, 17] },
  { goto: [31, 18] },
  { badge: [31, 17] },
  { goto: [31, 16] },
  { goto: [27, 4] },
  { inspect: 'leak-feed' },
  { goto: [27, 6] },
  { interact: 'ca-revoke' },
  { goto: [36, 6] },
  { interact: 'hsm-rekey' },
  { goto: [36, 11] },
  { inspect: 'pw-db' },
  { goto: [32, 14] },
  { interact: 'pw-bcrypt' },
  { goto: [20, 13] },
  { badge: [20, 12] },
  { goto: [16, 9] },
  { interact: 'card-export' },
  { goto: [23, 9] },
  { interact: 'backup-disk' },
  { goto: [20, 10] },
  { interact: 'vault-exit-console' },
  { wait: 0.2 },
  { goto: [20, 3] },
];

export const m06Teach: MissionTeaching = {
  tagline: 'Plaintext secrets, a stale certificate and a leaked key. Fix the crypto.',
  situation:
    'The audit found a certificate chain it cannot trust, a leaked VPN private key and card data outside the vault. The mission clock reads 2026-10-05.',
  orders: [
    { text: 'Trust only certificates that chain to a valid root.', objective: '1.4' },
    { text: 'Contain the leaked key so it can never vouch again.', objective: '1.4' },
    { text: 'Lock the vault data down at rest and in transit.', objective: '3.3' },
  ],
  keyTerms: [
    'certificate chain',
    'certificate authority',
    'self-signed certificate',
    'certificate revocation',
    'key rotation',
    'hashing',
    'salting',
    'key stretching',
    'tokenization',
    'encryption at rest',
    'multifactor authentication',
  ],
  lessons: {
    verify: {
      objective: '1.4',
      done: 'Certificate A links the leaf to KeyMaster Issuing CA 2 and then to GlobalTrust Root in the trust store. Its signatures and validity dates check out. Certificate B expired on 2026-09-01; Certificate C is self-signed and has no trusted CA chain.',
      missed: 'A certificate is trustworthy only when its signatures chain from the leaf through trusted issuing CAs to a root in the trust store, and its validity dates include the current date. Certificate B expired; Certificate C is self-signed.',
    },
    install: {
      objective: '1.4',
      done: 'You installed the certificate whose leaf-to-intermediate-to-root signatures validate and whose validity period includes 2026-10-05.',
      missed: 'The gateway needs a valid, unexpired certificate chained to a trusted root. An expired certificate or one signed only by itself will not establish trusted identity.',
    },
    leak: {
      objective: '1.4',
      done: 'The paste-site private key fingerprint matches the VPN certificate serial 0x5A11. Treat the key as compromised even though the certificate still reports good.',
      missed: 'The key alert was not investigated. Compare the leaked key fingerprint to the VPN certificate and act as soon as the compromise is confirmed.',
    },
    rotate: {
      objective: '1.4',
      done: 'You revoked serial 0x5A11 so CRL and OCSP report it revoked, then generated an independent key pair inside the HSM and issued a replacement certificate.',
      missed: 'A compromised certificate must be revoked, using CRL and OCSP status, and replaced with a new key pair. Renewing with the same leaked key leaves the attacker able to impersonate the VPN.',
    },
    passwords: {
      objective: '1.4',
      done: 'Each password now has a unique random salt and is processed by a key-stretched password hash such as bcrypt. Hashing is one-way; encryption is reversible and Base64 is only encoding.',
      missed: 'Do not encrypt or Base64-encode stored passwords. Store salted, key-stretched hashes so database theft does not reveal reusable passwords.',
    },
    data: {
      objective: '3.3',
      done: 'Masking only hides digits when displayed; tokenization replaces the card number with a token mapped in a controlled vault while refunds keep working. Full-disk encryption protects backup data at rest.',
      missed: 'The refund export still contains the full PAN and the backup drives are unencrypted. Masking is not tokenization: replace card numbers with mapped tokens and encrypt backup data at rest.',
    },
    seal: {
      objective: '3.3',
      done: 'The audit verifies the trusted certificate chain, revocation and new key, salted password hashes, tokenized card numbers and encrypted backups.',
      missed: 'The vault audit did not pass because one or more crypto controls is incomplete. Verify the certificate and key lifecycle, password hashing, tokenization and encryption at rest.',
    },
    exit: {
      objective: '4.6',
      done: 'You reached the exit after the audited changes were complete and the vault door had required the authorized role and MFA.',
      missed: 'The exit stays closed until the vault audit passes. Use only the approved role and satisfy both factors at the vault door.',
    },
    'bad-choice': {
      objective: '1.4',
      done: 'You rejected the wrong crypto choices. Encryption can be reversed, Base64 is encoding, and two knowledge questions are still one factor type.',
      missed: 'Encryption is reversible, Base64 is encoding rather than cryptography, and a password plus security question are both something you know. Use a salted, stretched hash and distinct factor types.',
    },
    'priority-miss': {
      objective: '1.4',
      done: 'You revoked the compromised certificate before rekeying. Revocation immediately tells clients to stop trusting the leaked key; the replacement uses a new key pair.',
      missed: 'Rekeying before revocation leaves the compromised certificate trusted during the gap. Revoke first, then issue a replacement with an independent key pair.',
    },
  },
  examTip:
    'Revoke + rekey on compromise; expired or self-signed = untrusted; passwords are salted and stretched hashes, not encryption; tokenization keeps real card numbers out of downstream systems.',
};
